//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SCIM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemForCrossDomainIdentityManagementServiceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemForCrossDomainIdentityManagementServiceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SCIM.SystemForCrossDomainIdentityManagementServiceResources", typeof(SystemForCrossDomainIdentityManagementServiceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering by this attribute is not supported: {0}..
        /// </summary>
        public static string ExceptionFilterAttributePathNotSupportedTemplate {
            get {
                return ResourceManager.GetString("ExceptionFilterAttributePathNotSupportedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a query with exactly one filter is supported..
        /// </summary>
        public static string ExceptionFilterCount {
            get {
                return ResourceManager.GetString("ExceptionFilterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter is not supported..
        /// </summary>
        public static string ExceptionFilterNotSupported {
            get {
                return ResourceManager.GetString("ExceptionFilterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This filter operator is not supported: {0}..
        /// </summary>
        public static string ExceptionFilterOperatorNotSupportedTemplate {
            get {
                return ResourceManager.GetString("ExceptionFilterOperatorNotSupportedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A batch is invalid..
        /// </summary>
        public static string ExceptionInvalidBatch {
            get {
                return ResourceManager.GetString("ExceptionInvalidBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context is invalid..
        /// </summary>
        public static string ExceptionInvalidContext {
            get {
                return ResourceManager.GetString("ExceptionInvalidContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An identifier is invalid..
        /// </summary>
        public static string ExceptionInvalidIdentifier {
            get {
                return ResourceManager.GetString("ExceptionInvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An operation is invalid..
        /// </summary>
        public static string ExceptionInvalidOperation {
            get {
                return ResourceManager.GetString("ExceptionInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation with this identifier is not valid: {0}..
        /// </summary>
        public static string ExceptionInvalidOperationTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidOperationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameters are invalid..
        /// </summary>
        public static string ExceptionInvalidParameters {
            get {
                return ResourceManager.GetString("ExceptionInvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is invalid..
        /// </summary>
        public static string ExceptionInvalidRequest {
            get {
                return ResourceManager.GetString("ExceptionInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource is invalid..
        /// </summary>
        public static string ExceptionInvalidResource {
            get {
                return ResourceManager.GetString("ExceptionInvalidResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response is invalid..
        /// </summary>
        public static string ExceptionInvalidResponse {
            get {
                return ResourceManager.GetString("ExceptionInvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state is invalid..
        /// </summary>
        public static string ExceptionInvalidState {
            get {
                return ResourceManager.GetString("ExceptionInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested state transition is invalid..
        /// </summary>
        public static string ExceptionInvalidStateTransition {
            get {
                return ResourceManager.GetString("ExceptionInvalidStateTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is not supported: {0}..
        /// </summary>
        public static string ExceptionMethodNotSupportedTemplate {
            get {
                return ResourceManager.GetString("ExceptionMethodNotSupportedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The monitoring behavior has not been properly initialized..
        /// </summary>
        public static string ExceptionNotInitializedMonitoringBehavior {
            get {
                return ResourceManager.GetString("ExceptionNotInitializedMonitoringBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider behavior has not been properly initialized..
        /// </summary>
        public static string ExceptionNotInitializedProviderBehavior {
            get {
                return ResourceManager.GetString("ExceptionNotInitializedProviderBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagination is not supported for this type of resource: {0}.
        /// </summary>
        public static string ExceptionPaginationIsNotSupportedTemplate {
            get {
                return ResourceManager.GetString("ExceptionPaginationIsNotSupportedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query is not supported..
        /// </summary>
        public static string ExceptionQueryNotSupported {
            get {
                return ResourceManager.GetString("ExceptionQueryNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string HeaderTemplate {
            get {
                return ResourceManager.GetString("HeaderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been read..
        /// </summary>
        public static string InformationRead {
            get {
                return ResourceManager.GetString("InformationRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing of this request was completed: {0}.  
        ///
        ///The status code of the response was {1}.
        /// </summary>
        public static string InformationRequestProcessedTemplate {
            get {
                return ResourceManager.GetString("InformationRequestProcessedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request was received: {0}..
        /// </summary>
        public static string InformationRequestReceivedTemplate {
            get {
                return ResourceManager.GetString("InformationRequestReceivedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been written..
        /// </summary>
        public static string InformationWrote {
            get {
                return ResourceManager.GetString("InformationWrote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}
        ///{2}.
        /// </summary>
        public static string MessageTemplate {
            get {
                return ResourceManager.GetString("MessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}@.
        /// </summary>
        public static string MonitorCorrelationIdentifierPrefixTemplate {
            get {
                return ResourceManager.GetString("MonitorCorrelationIdentifierPrefixTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} (Critical? {2}).
        /// </summary>
        public static string MonitorOutputExceptionTemplate {
            get {
                return ResourceManager.GetString("MonitorOutputExceptionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} (Verbose? {2}).
        /// </summary>
        public static string MonitorOutputInformationTemplate {
            get {
                return ResourceManager.GetString("MonitorOutputInformationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string MonitorOutputTemplate {
            get {
                return ResourceManager.GetString("MonitorOutputTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource {0} not found..
        /// </summary>
        public static string ResourceNotFoundTemplate {
            get {
                return ResourceManager.GetString("ResourceNotFoundTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string SeparatorHeaderValues {
            get {
                return ResourceManager.GetString("SeparatorHeaderValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied watermark did not match the expected watermark: 
        ///Supplied: 
        ///{0}
        ///Received: 
        ///{1}.
        /// </summary>
        public static string WarningUnexpectedWatermarkTemplate {
            get {
                return ResourceManager.GetString("WarningUnexpectedWatermarkTemplate", resourceCulture);
            }
        }
    }
}
