//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SCIM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemForCrossDomainIdentityManagementProtocolResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemForCrossDomainIdentityManagementProtocolResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SCIM.SystemForCrossDomainIdentityManagementProtocolResources", typeof(SystemForCrossDomainIdentityManagementProtocolResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This filter is invalid: {0}..
        /// </summary>
        internal static string ExceptionInvalidFilterTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidFilterTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operator is not supported: {0}..
        /// </summary>
        internal static string ExceptionInvalidOperatorTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidOperatorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This path is invalid: {0}..
        /// </summary>
        internal static string ExceptionInvalidPathTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidPathTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is invalid..
        /// </summary>
        internal static string ExceptionInvalidRequest {
            get {
                return ResourceManager.GetString("ExceptionInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resource is invalid..
        /// </summary>
        internal static string ExceptionInvalidResource {
            get {
                return ResourceManager.GetString("ExceptionInvalidResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This count value is invalid: {0}.  A non-negative number is expected..
        /// </summary>
        internal static string ExceptionInvalidSearchRequestCountTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidSearchRequestCountTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sort order value is invalid: {0}..
        /// </summary>
        internal static string ExceptionInvalidSortOrderTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidSortOrderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This start index value is invalid: {0}.  The start index is a 1-based index..
        /// </summary>
        internal static string ExceptionInvalidStartIndexTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidStartIndexTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is invalid..
        /// </summary>
        internal static string ExceptionInvalidValue {
            get {
                return ResourceManager.GetString("ExceptionInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bulk operation must have a unique identifier..
        /// </summary>
        internal static string ExceptionUnidentifiableOperation {
            get {
                return ResourceManager.GetString("ExceptionUnidentifiableOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema could not be identified..
        /// </summary>
        internal static string ExceptionUnidentifiableSchema {
            get {
                return ResourceManager.GetString("ExceptionUnidentifiableSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}..
        /// </summary>
        internal static string ResourceIdentifierTemplate {
            get {
                return ResourceManager.GetString("ResourceIdentifierTemplate", resourceCulture);
            }
        }
    }
}
